### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by bogganj94** [LeonHeidelbach/ttv_adEraser#1]
Hello after adding the extension and reloading the twitch page where i want ads blocked i get this error. at first the theatre mode button was gone but refreshing the page again brought the theatre mode back.  

Stack Trace: 
`JS/cnt.js:284 (anonymous function)
`

Lines highlighted by chrome are
`insertSiblingNodeBefore(theaterModeButton,fullScreenModeButton.parentNode);
`

**Comment by LeonHeidelbach** [comment]
Hey,
thank you for letting me know. Which version of the extension are you currently using? Are you using v.1.1 from the dev_build branch or v.1.0 from main? This error can occur when the embed player loads and the theater mode button has not yet appeared on the original player. I did personally never have that error before but I will look into it. Reloading the page can resolve the issue when the theater mode button loads in time.

**Comment by LeonHeidelbach** [comment]
This issue has been resolved in the latest dev_build. Note that there might still be some bugs in the dev_build.

https://github.com/LeonHeidelbach/ttv_adEraser/tree/dev_build
