### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by Defxult** [LeonHeidelbach/ttv_adEraser#25]
With the extension enabled, the stream never loads. Only audio comes through

**Comment by Sota4077** [comment]
Yup.  I can report the same issue.  I'm sure Twitch tweaked something yet again.  I have it on Chrome, Edge and Firefox and it does it on all three if that helps.

**Comment by xDrev** [comment]
Having same issue.

**Comment by agentdouble0** [comment]
Same issue here

**Comment by psifertex** [comment]
Why is this closed as completed? I'm still seeing the same behavior. Just uninstalled and reinstalled the plugin from the chrome store. Is that not the latest version?
