### ISSUE TITLE
Video Player Not Using Full Name

### ISSUE THREAD

**Issue by Outsanity** [LeonHeidelbach/ttv_adEraser#3]
Hard to describe unless I'm the only one to have this issue but, seems that if a stream has a spaced (with underscores) name, it only displays the first word of the name resulting is a black video or possibly a wrong channel video if one were to exist as showned in the screenshot.
![opera_2020-12-22_17-50-58-EDITED](https://user-images.githubusercontent.com/9843093/102943901-f90ed900-447e-11eb-9a51-59cf644eb4a8.png)

**Comment by LeonHeidelbach** [comment]
This issue has been fixed a while ago. If you are still having this issue after downloading the Chrome Web Store version or installing either the dev_build or main version from my GitHub let me know.
