### ISSUE TITLE
Theater mode broken in dev build 1.1

### ISSUE THREAD

**Issue by Anonanon** [LeonHeidelbach/ttv_adEraser#4]
Theater mode chops off a bottom portion of the video, which is a problem in itself, but you also can't access the player controls anymore until you refresh the page again. This happens in a small window size but also when maximized too. What I ended up doing for now is popping out the video using Chrome's Picture In Picture function, but this also breaks your mid roll swapping workaround. Might want to take a look at the theater mode video not scaling to properly according to the frame in various sizes and aspect ratios.

![1273 chrome  2020-12-25   03 34 11AM](https://user-images.githubusercontent.com/1048428/103128172-341d3200-4662-11eb-9461-c1caecd9de17.png)

**Comment by LeonHeidelbach** [comment]
I have just fixed this issue. Try to download the new dev_build version of the extension. Note that there might still be some bugs in the dev_build.

https://github.com/LeonHeidelbach/ttv_adEraser/tree/dev_build
