### ISSUE TITLE
adblock no longer working

### ISSUE THREAD

**Issue by savageduckerino** [LeonHeidelbach/ttv_adEraser#5]
as of 12/25 3:10 pm i'm just getting this https://cdn.discordapp.com/attachments/588109094515245079/792124050083151872/unknown.png

**Comment by Suprcheese** [comment]
> 
> 
> as of 12/25 3:10 pm i'm just getting this https://cdn.discordapp.com/attachments/588109094515245079/792124050083151872/unknown.png

Try this other solution instead: https://github.com/pixeltris/TwitchAdSolutions

**Comment by LeonHeidelbach** [comment]
You are probably on v.1.0 of the extension. Try out the dev_build, where I have implemented new ad blocking solutions that work again. Note that there are still some bugs in the dev_build that I will have to address until it is fully stable.

https://github.com/LeonHeidelbach/ttv_adEraser/tree/dev_build
