### ISSUE TITLE
Video quality maxed and volume muted after an ad block in dev build 1.2

### ISSUE THREAD

**Issue by Anonanon** [LeonHeidelbach/ttv_adEraser#6]
When the ad "block" is triggered (when the stream is swapping) it loads as Source quality and volume muted by default. While the ad blocking technically does work, the viewing experience still needs baby sitting re-selecting the quality and volume again.

**Comment by LeonHeidelbach** [comment]
Thank you for pointing out those issues. I will look into them and push an update as soon as possible.

**Comment by LeonHeidelbach** [comment]
Both issues have been fixed in the latest commit.
