### ISSUE TITLE
Starting/First Ad Plays, But Other Ads Are Still Blocked

### ISSUE THREAD

**Issue by Zzakal** [LeonHeidelbach/ttv_adEraser#8]
As the title says. The first ad plays and can't be skipped, I tried refreshing and reopening the browser, doesn't stop the first ad when opening a stream. After the first ad plays, then everything works fine on that stream (following ads are blocked).

Notes: The ads are automatically muted, but not the stream. You often see the twitch adblock detected screen flash for a second then is replaced with an ad, only on the first/starting ad for that stream.

**Comment by LeonHeidelbach** [comment]
Yes, if you have a look at the [changelog](https://github.com/LeonHeidelbach/ttv_adEraser#changelog) this can happen if a pre roll ad plays at the same time as the purple screen is shown after switching streams. Unfortunately there is currently no better way of getting rid of ads and this should only happen occasionally. Mid rolls however should be completely removed using the implemented ad block method. As soon as I find a better way of getting rid of ads and the purple screen I will of course update the extension.

**Comment by Zzakal** [comment]
Thank you for the response and information.
